### ISSUE TITLE
2 examples of not working

### ISSUE THREAD

**Issue by psugihara** [hyperjumptech/favicon-fetcher#2]
Hey! Love this little lib, thanks for publishing. ⛰️ 

Hope a couple non-working test-cases are useful:
`["https://www.kiddom.co/","https://www.pandadoc.com/"]`

Safari shows a favicon for both but getFavicon returns nothing.

FWIW I had a test list of 21, so 90% hit rate and much better than just trying to hit /favicon.ico

**Comment by dennypradipta** [comment]
I've added a strategy called 'http' in the latest version (v1.0.4) where it will find the first icon inside the `<link rel="icon">` element, give it a try. If there is a bug, feel free to reopen this issue again :)

**Comment by psugihara** [comment]
wow thanks!
